name: spring-boot-rabbitmq

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rabbitmq-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-rabbitmq
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE_NAME=demo_queue
      - RABBITMQ_EXCHANGE_NAME=demo_exchange
      - RABBITMQ_ROUTING_KEY=demo_routing_key
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge
